In [36]:
import pandas as pd
file_path = '/vol/miltank/projects/practical_wise2526/knee-osteoarthritis-severity/OAI_Dataset/AllClinical00.txt'
df = pd.read_csv(file_path, sep='|')
df.head()

,ID,VERSION,V00BLDCOLL,V00BLDHRS1,V00BLDHRS2,V00BLDRAW1,V00BLDRAW2,V00BLSURD1,V00BLSURD2,V00CITRATE,...,V00PASE4,V00PASE4HR,V00PASE5,V00PASE5HR,V00PASE6,V00PASE6HR,V00WEEKWK,V00WKHR7CV,V00WORK7,V00WORKAMT
0,9000099,0.2.3,1: Sample at 1st collection only,35400.0,NaN,1: Yes,.: Missing Form/Incomplete Workbook,NaN,NaN,1: Sample at 1st collection only,...,0: Never,.: Missing Form/Incomplete Workbook,3: Often (5-7 days),1: Less than 1 hour,2: Sometimes (3-4 days),1: Less than 1 hour,52.0,50.0,1: Yes,1: Sitting
1,9000296,0.2.3,1: Sample at 1st collection only,30780.0,NaN,1: Yes,.: Missing Form/Incomplete Workbook,NaN,NaN,1: Sample at 1st collection only,...,0: Never,.: Missing Form/Incomplete Workbook,0: Never,.: Missing Form/Incomplete Workbook,0: Never,.: Missing Form/Incomplete Workbook,52.0,50.0,1: Yes,2: Sitting/standing/walking
2,9000622,0.2.3,1: Sample at 1st collection only,33900.0,NaN,1: Yes,.: Missing Form/Incomplete Workbook,NaN,NaN,1: Sample at 1st collection only,...,0: Never,.: Missing Form/Incomplete Workbook,0: Never,.: Missing Form/Incomplete Workbook,0: Never,.: Missing Form/Incomplete Workbook,NaN,0.0,0: No,.: Missing Form/Incomplete Workbook
3,9000798,0.2.3,1: Sample at 1st collection only,26400.0,NaN,1: Yes,.: Missing Form/Incomplete Workbook,NaN,NaN,1: Sample at 1st collection only,...,0: Never,.: Missing Form/Incomplete Workbook,0: Never,.: Missing Form/Incomplete Workbook,0: Never,.: Missing Form/Incomplete Workbook,52.0,40.0,1: Yes,3: Walking/handling <50 lbs
4,9001104,0.2.3,1: Sample at 1st collection only,35100.0,NaN,1: Yes,.: Missing Form/Incomplete Workbook,NaN,NaN,1: Sample at 1st collection only,...,0: Never,.: Missing Form/Incomplete Workbook,0: Never,.: Missing Form/Incomplete Workbook,3: Often (5-7 days),1: Less than 1 hour,NaN,0.0,0: No,.: Missing Form/Incomplete Workbook

In [37]:
clinical= df.copy()

In [38]:
# Filter the dataframe to keep only the columns specified in VARIABLE_DESCRIPTIONS
import json
# Load the JSON file
with open('variables.json', 'r') as file:
	variables = json.load(file)
columns_to_keep= ['ID']
# Extract the columns to keep
columns_to_keep.extend(variables['VARIABLE_DESCRIPTIONS'].keys())
clinical = clinical[columns_to_keep]

In [39]:
clinical.head()

,ID,V00WOMTSR,V00WOMTSL,V00KOOSFSR,V00KOOSKPL,V00KOOSKPR,V00KOOSYML,V00KOOSYMR,V00KOOSQOL,P01KRSL,...,P01LRR,P02KSURGCV,P01SVLKJSL,P01SVLKJSM,P01SVRKJSL,P01SVRKJSM,P01SVLKOST,P01SVRKOST,P01OAGRDL,P01OAGRDR
0,9000099,14.0,0.0,40.0,100.0,77.8,100.0,67.9,25.0,0: No,...,.: Missing Form/Incomplete Workbook,0: No,"2: 2 (severe, OARSI grade 3)","0: 0 (normal, OARSI grade 0)","0: 0 (normal, OARSI grade 0)","1: 1 (narrowed, OARSI grade 1-2)","2: 2 (definite, OARSI grade 1-3)","2: 2 (definite, OARSI grade 1-3)",4: Severe,3: Moderate
1,9000296,0.0,0.0,100.0,100.0,100.0,100.0,100.0,100.0,0: No,...,.: Missing Form/Incomplete Workbook,0: No,"0: 0 (normal, OARSI grade 0)","1: 1 (narrowed, OARSI grade 1-2)","0: 0 (normal, OARSI grade 0)","0: 0 (normal, OARSI grade 0)","1: 1 (possible, minute)","2: 2 (definite, OARSI grade 1-3)",1: Possible,2: Definite - mild
2,9000622,20.9,0.0,50.0,100.0,75.0,100.0,82.1,50.0,.: Missing Form/Incomplete Workbook,...,.: Missing Form/Incomplete Workbook,0: No,"0: 0 (normal, OARSI grade 0)","0: 0 (normal, OARSI grade 0)","0: 0 (normal, OARSI grade 0)","0: 0 (normal, OARSI grade 0)",0: 0 (none),"2: 2 (definite, OARSI grade 1-3)",0: Normal,2: Definite - mild
3,9000798,0.0,30.0,66.7,59.4,100.0,57.1,100.0,43.8,0: No,...,.: Missing Form/Incomplete Workbook,0: No,"0: 0 (normal, OARSI grade 0)","2: 2 (severe, OARSI grade 3)","0: 0 (normal, OARSI grade 0)","0: 0 (normal, OARSI grade 0)","2: 2 (definite, OARSI grade 1-3)","2: 2 (definite, OARSI grade 1-3)",4: Severe,2: Definite - mild
4,9001104,33.0,14.0,37.5,100.0,69.4,85.7,60.7,37.5,.: Missing Form/Incomplete Workbook,...,.: Missing Form/Incomplete Workbook,0: No,"0: 0 (normal, OARSI grade 0)","0: 0 (normal, OARSI grade 0)","0: 0 (normal, OARSI grade 0)","2: 2 (severe, OARSI grade 3)",0: 0 (none),"2: 2 (definite, OARSI grade 1-3)",0: Normal,4: Severe

In [40]:
# Map for 'SURGERY' variables
surgery_map = {'1: Yes': 1, '0: No': 0, '.: Missing Form/Incomplete Workbook': pd.NA}
clinical[variables['VARIABLES']['SURGERY']] = clinical[variables['VARIABLES']['SURGERY']].replace(surgery_map)

# Map for 'JOINT_SPACE_NARROWING' variables
joint_space_narrowing_map = {
    '2: 2 (severe, OARSI grade 3)': 2,
    '0: 0  (normal, OARSI grade 0)': 0,
    '1: 1 (narrowed, OARSI grade 1-2)': 1,
    '.: Missing Form/Incomplete Workbook': pd.NA
}
clinical[variables['VARIABLES']['JOINT_SPACE_NARROWING']] = clinical[variables['VARIABLES']['JOINT_SPACE_NARROWING']].replace(joint_space_narrowing_map)

# Map for 'OSTEOPHYTES' variables
osteophytes_map = {
    '2: 2 (definite, OARSI grade 1-3)': 2,
    '1: 1 (possible, minute)': 1,
    '0: 0 (none)': 0,
    '.: Missing Form/Incomplete Workbook': pd.NA
}
clinical[variables['VARIABLES']['OSTEOPHYTES']] = clinical[variables['VARIABLES']['OSTEOPHYTES']].replace(osteophytes_map)

# Map for 'KL_GRADE' variables 
kl_grade_map = {
    '0: Normal': 0,
    '1: Possible': 1,
    '2: Definite - mild': 2,
    '3: Moderate': 3,
    '4: Severe': 4,
    '.: Missing Form/Incomplete Workbook': pd.NA
}
clinical[variables['VARIABLES']['KL_GRADE']] = clinical[variables['VARIABLES']['KL_GRADE']].replace(kl_grade_map)

In [41]:
clinical.head()

,ID,V00WOMTSR,V00WOMTSL,V00KOOSFSR,V00KOOSKPL,V00KOOSKPR,V00KOOSYML,V00KOOSYMR,V00KOOSQOL,P01KRSL,...,P01LRR,P02KSURGCV,P01SVLKJSL,P01SVLKJSM,P01SVRKJSL,P01SVRKJSM,P01SVLKOST,P01SVRKOST,P01OAGRDL,P01OAGRDR
0,9000099,14.0,0.0,40.0,100.0,77.8,100.0,67.9,25.0,0: No,...,.: Missing Form/Incomplete Workbook,0,2,0,0,1,2,2,4,3
1,9000296,0.0,0.0,100.0,100.0,100.0,100.0,100.0,100.0,0: No,...,.: Missing Form/Incomplete Workbook,0,0,1,0,0,1,2,1,2
2,9000622,20.9,0.0,50.0,100.0,75.0,100.0,82.1,50.0,.: Missing Form/Incomplete Workbook,...,.: Missing Form/Incomplete Workbook,0,0,0,0,0,0,2,0,2
3,9000798,0.0,30.0,66.7,59.4,100.0,57.1,100.0,43.8,0: No,...,.: Missing Form/Incomplete Workbook,0,0,2,0,0,2,2,4,2
4,9001104,33.0,14.0,37.5,100.0,69.4,85.7,60.7,37.5,.: Missing Form/Incomplete Workbook,...,.: Missing Form/Incomplete Workbook,0,0,0,0,2,0,2,0,4

In [42]:
#after this point we notice that the following columns have over 4000 missing values
# (apart from the last one which is over 1200 so still a relevant amount to fake):
# P01KRSL, P01KRSR, P01MENL, P01MENR, P01LRL, P01LRR,V00KOOSFSR
#so we remove them from the dataset
columns_to_drop = ['P01KRSL', 'P01KRSR', 'P01MENL', 'P01MENR', 'P01LRL', 'P01LRR','V00KOOSFSR']
clinical = clinical.drop(columns=columns_to_drop)

In [43]:
clinical.head()

,ID,V00WOMTSR,V00WOMTSL,V00KOOSKPL,V00KOOSKPR,V00KOOSYML,V00KOOSYMR,V00KOOSQOL,P01KSURGL,P01KSURGR,P02KSURGCV,P01SVLKJSL,P01SVLKJSM,P01SVRKJSL,P01SVRKJSM,P01SVLKOST,P01SVRKOST,P01OAGRDL,P01OAGRDR
0,9000099,14.0,0.0,100.0,77.8,100.0,67.9,25.0,1,0,0,2,0,0,1,2,2,4,3
1,9000296,0.0,0.0,100.0,100.0,100.0,100.0,100.0,1,0,0,0,1,0,0,1,2,1,2
2,9000622,20.9,0.0,100.0,75.0,100.0,82.1,50.0,0,0,0,0,0,0,0,0,2,0,2
3,9000798,0.0,30.0,59.4,100.0,57.1,100.0,43.8,1,0,0,0,2,0,0,2,2,4,2
4,9001104,33.0,14.0,100.0,69.4,85.7,60.7,37.5,0,0,0,0,0,0,2,0,2,0,4

In [44]:
clinical.isna().sum().sort_values(ascending=False).head(20)

P01OAGRDR     39
P01SVRKJSL    38
P01SVRKOST    38
P01SVRKJSM    37
V00WOMTSL     28
P01OAGRDL     27
P01SVLKJSM    26
P01SVLKOST    26
P01SVLKJSL    25
V00WOMTSR     21
P01KSURGL      9
P01KSURGR      8
P02KSURGCV     5
V00KOOSKPR     3
V00KOOSKPL     2
V00KOOSQOL     1
ID             0
V00KOOSYML     0
V00KOOSYMR     0
dtype: int64

In [45]:
# Replace missing values with the median for the specified columns
median_columns = ['P01SVRKOST', 'P01SVRKJSL', 'P01SVRKJSM', 'P01SVLKOST', 'P01SVLKJSL', 'P01SVLKJSM', 'P01OAGRDL', 'P01OAGRDR']
for col in median_columns:
    clinical[col] = clinical[col].fillna(clinical[col].median())

import math

# Replace missing values with the mean for the specified columns
mean_columns = ['V00WOMTSR', 'V00WOMTSL', 'V00KOOSKPL', 'V00KOOSKPR', 'V00KOOSQOL']
for col in mean_columns:
    clinical[col] = clinical[col].fillna(round(clinical[col].mean()))
    

# Replace missing values with 0 for the specified columns
zero_columns = ['P01KSURGL', 'P01KSURGR', 'P02KSURGCV']
for col in zero_columns:
    clinical[col] = clinical[col].fillna(0)

/tmp/ipykernel_3469416/3709492812.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  clinical[col] = clinical[col].fillna(clinical[col].median())
/tmp/ipykernel_3469416/3709492812.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  clinical[col] = clinical[col].fillna(clinical[col].median())
/tmp/ipykernel_3469416/3709492812.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  clinical[col] = clinical[col].fillna(clinical[col].median())
/tmp/ipykernel_3469416/3709492812.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  clinical[col] = clinical[col].fillna(clinical[col].median())
/tmp/ipykernel_3469416/3709492812.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  clinical[col] = clinical[col].fillna(clinical[col].median())
/tmp/ipykernel_3469416/3709492812.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  clinical[col] = clinical[col].fillna(clinical[col].median())
/tmp/ipykernel_3469416/3709492812.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  clinical[col] = clinical[col].fillna(clinical[col].median())
/tmp/ipykernel_3469416/3709492812.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  clinical[col] = clinical[col].fillna(clinical[col].median())
/tmp/ipykernel_3469416/3709492812.py:17: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  clinical[col] = clinical[col].fillna(0)

In [46]:
#save the final dataset
clinical.to_csv('csv/clinical00_cleaned.csv', index=False)

In [47]:
# Check if the column exists in the dataframe
if 'P01SVLKJSM' in clinical.columns:
	print(clinical['P01SVLKJSM'].unique())
else:
	print("Column 'P01SVLKJSM' does not exist in the dataframe. Available columns are:")
	print(clinical.columns)

[0. 1. 2.]